---
- name: Install helm
  hosts: localhost
  connection: local
  become: yes
  become_user: vagrant

  tasks:
  - name: Install helm
    become_user: root
    unarchive:
      src: https://get.helm.sh/helm-v3.12.2-linux-amd64.tar.gz
      dest: /usr/local/bin
      extra_opts: "--strip-components=1"
      owner: root
      group: root
      mode: 0755
      remote_src: true
    args:
      creates: /usr/local/bin/helm

  - name: Add repositories to helm
    shell: |
      helm repo add stable https://charts.helm.sh/stable --force-update
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

  - name: Install Prometheus
    command: helm install prometheus prometheus-community/prometheus