---
- name: Setup Secrets
  hosts: localhost
  connection: local
  become_user: vagrant
  vars_files:
    - ../vars/secrets/slack.yml

  tasks:
  - name: Create alertmanager secrets 
    shell: |
      kubectl create secret generic alertmanager-secrets \
      --from-literal="slack-api-url={{ slack_api_url }}"
