apiVersion: v1
kind: Service
metadata:
  name: alert-manager-ext
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9093
      nodePort: 30092
